'Public Class airportSetClass

'    Inherits Hashtable

'    Public Shared ReadOnly Property Instance() As airportSetClass
'        Get
'            If singlet Is Nothing Then
'                singlet = New airportSetClass
'            End If
'            Return singlet
'        End Get
'    End Property


'    Public airportList() As locationClass = { _
'        New locationClass("AAL", timeZoneName.CentralEuropean), _
'        New locationClass("AAR", timeZoneName.CentralEuropean), _
'        New locationClass("ABE", timeZoneName.EasternUS), _
'        New locationClass("ABR", timeZoneName.CentralUS), _
'        New locationClass("ABZ", timeZoneName.GreenwichMeanTime), _
'        New locationClass("ACA", timeZoneName.MexicoCity), _
'        New locationClass("ACK", timeZoneName.EasternUS), _
'        New locationClass("ACV", timeZoneName.PacificUS), _
'        New locationClass("ACY", timeZoneName.EasternUS), _
'        New locationClass("AGS", timeZoneName.EasternUS), _
'        New locationClass("AHN", timeZoneName.EasternUS), _
'        New locationClass("AKL", timeZoneName.NewZealand), _
'        New locationClass("ALB", timeZoneName.EasternUS), _
'        New locationClass("ALC", timeZoneName.CentralEuropean), _
'        New locationClass("AMA", timeZoneName.CentralUS), _
'        New locationClass("AMM", timeZoneName.HelsinkiRiga), _
'        New locationClass("AMS", timeZoneName.CentralEuropean), _
'        New locationClass("ANC", timeZoneName.Alaska), _
'        New locationClass("ANU", timeZoneName.AtlanticUS), _
'        New locationClass("AOO", timeZoneName.EasternUS), _
'        New locationClass("APF", timeZoneName.CentralEuropean), _
'        New locationClass("APW", timeZoneName.SamoaMidway), _
'        New locationClass("ART", timeZoneName.EasternUS), _
'        New locationClass("ARN", timeZoneName.CentralEuropean), _
'        New locationClass("ASU", timeZoneName.Carcas), _
'        New locationClass("ATH", timeZoneName.AthensIstanbul), _
'        New locationClass("ATL", timeZoneName.EasternUS), _
'        New locationClass("ATW", timeZoneName.CentralUS), _
'        New locationClass("AUA", timeZoneName.AtlanticUS), _
'        New locationClass("AUG", timeZoneName.EasternUS), _
'        New locationClass("AUH", timeZoneName.AbuDhabi), _
'        New locationClass("AUS", timeZoneName.CentralUS), _
'        New locationClass("AVL", timeZoneName.EasternUS), _
'        New locationClass("AVP", timeZoneName.EasternUS), _
'        New locationClass("AXA", timeZoneName.AtlanticUS), _
'        New locationClass("AZO", timeZoneName.EasternUS), _
'        New locationClass("BAH", timeZoneName.Moscow), _
'        New locationClass("BCD", timeZoneName.Perth), _
'        New locationClass("BCN", timeZoneName.CentralEuropean), _
'        New locationClass("BDA", timeZoneName.Atlantic), _
'        New locationClass("BDL", timeZoneName.EasternUS), _
'        New locationClass("BED", timeZoneName.EasternUS), _
'        New locationClass("BEG", timeZoneName.CentralEuropean), _
'        New locationClass("BEY", timeZoneName.Cairo), _
'        New locationClass("BFD", timeZoneName.EasternUS), _
'        New locationClass("BFS", timeZoneName.GreenwichMeanTime), _
'        New locationClass("BGI", timeZoneName.AtlanticUS), _
'        New locationClass("BGM", timeZoneName.EasternUS), _
'        New locationClass("BGO", timeZoneName.CentralEuropean), _
'        New locationClass("BGR", timeZoneName.EasternUS), _
'        New locationClass("BHB", timeZoneName.EasternUS), _
'        New locationClass("BHM", timeZoneName.CentralUS), _
'        New locationClass("BHX", timeZoneName.GreenwichMeanTime), _
'        New locationClass("BIL", timeZoneName.MountainUS), _
'        New locationClass("BIS", timeZoneName.CentralUS), _
'        New locationClass("BJS", timeZoneName.HongKong), _
'        New locationClass("BKW", timeZoneName.EasternUS), _
'        New locationClass("BKK", timeZoneName.BankokHanoi), _
'        New locationClass("BLF", timeZoneName.EasternUS), _
'        New locationClass("BMI", timeZoneName.GreenwichMeanTime), _
'        New locationClass("BNA", timeZoneName.CentralUS), _
'        New locationClass("BNE", timeZoneName.Queensland), _
'        New locationClass("BOG", timeZoneName.BogotaLima), _
'        New locationClass("BOI", timeZoneName.MountainUS), _
'        New locationClass("BOS", timeZoneName.EasternUS), _
'        New locationClass("BQN", timeZoneName.AtlanticUS), _
'        New locationClass("BQU", timeZoneName.CapeTown), _
'        New locationClass("BRE", timeZoneName.CentralEuropean), _
'        New locationClass("BRU", timeZoneName.CentralEuropean), _
'        New locationClass("BTM", timeZoneName.MountainUS), _
'        New locationClass("BTR", timeZoneName.CentralUS), _
'        New locationClass("BTV", timeZoneName.EasternUS), _
'        New locationClass("BUD", timeZoneName.CentralEuropean), _
'        New locationClass("BUE", timeZoneName.Brasilia), _
'        New locationClass("BUF", timeZoneName.EasternUS), _
'        New locationClass("BUH", timeZoneName.Asia), _
'        New locationClass("BUR", timeZoneName.PacificUS), _
'        New locationClass("BWI", timeZoneName.EasternUS), _
'        New locationClass("BZE", timeZoneName.CentralAmerica), _
'        New locationClass("CAE", timeZoneName.EasternUS), _
'        New locationClass("CAI", timeZoneName.Cairo), _
'        New locationClass("CAK", timeZoneName.EasternUS), _
'        New locationClass("CBE", timeZoneName.EasternUS), _
'        New locationClass("CBG", timeZoneName.GreenwichMeanTime), _
'        New locationClass("CCS", timeZoneName.Carcas), _
'        New locationClass("CDG", timeZoneName.CentralEuropean), _
'        New locationClass("CGN", timeZoneName.CentralEuropean), _
'        New locationClass("CHA", timeZoneName.EasternUS), _
'        New locationClass("CHC", timeZoneName.NewZealand), _
'        New locationClass("CHO", timeZoneName.EasternUS), _
'        New locationClass("CHS", timeZoneName.EasternUS), _
'        New locationClass("CID", timeZoneName.CentralUS), _
'        New locationClass("CJJ", timeZoneName.Asia), _
'        New locationClass("CKB", timeZoneName.EasternUS), _
'        New locationClass("CLE", timeZoneName.EasternUS), _
'        New locationClass("CLT", timeZoneName.EasternUS), _
'        New locationClass("CMH", timeZoneName.EasternUS), _
'        New locationClass("CPH", timeZoneName.CentralEuropean), _
'        New locationClass("CPT", timeZoneName.CapeTown), _
'        New locationClass("CPX", timeZoneName.AtlanticUS), _
'        New locationClass("CRW", timeZoneName.EasternUS), _
'        New locationClass("CTA", timeZoneName.CentralEuropean), _
'        New locationClass("CUN", timeZoneName.MexicoCity), _
'        New locationClass("CVG", timeZoneName.EasternUS), _
'        New locationClass("CWA", timeZoneName.CentralUS), _
'        New locationClass("CZA", timeZoneName.MexicoCity), _
'        New locationClass("CZM", timeZoneName.MexicoCity), _
'        New locationClass("DAC", timeZoneName.SriLanka), _
'        New locationClass("DAM", timeZoneName.Cairo), _
'        New locationClass("DAY", timeZoneName.EasternUS), _
'        New locationClass("DBN", timeZoneName.EasternUS), _
'        New locationClass("DCA", timeZoneName.EasternUS), _
'        New locationClass("DDC", timeZoneName.CentralUS), _
'        New locationClass("DEN", timeZoneName.MountainUS), _
'        New locationClass("DFW", timeZoneName.CentralUS), _
'        New locationClass("DHD", timeZoneName.EasternUS), _
'        New locationClass("DLH", timeZoneName.CentralUS), _
'        New locationClass("DME", timeZoneName.Moscow), _
'        New locationClass("DMM", timeZoneName.Riyadh), _
'        New locationClass("DOH", timeZoneName.Moscow), _
'        New locationClass("DSM", timeZoneName.CentralUS), _
'        New locationClass("DTW", timeZoneName.EasternUS), _
'        New locationClass("DUB", timeZoneName.GreenwichMeanTime), _
'        New locationClass("DUJ", timeZoneName.EasternUS), _
'        New locationClass("DUR", timeZoneName.CapeTown), _
'        New locationClass("DXB", timeZoneName.WesternAsian), _
'        New locationClass("EAU", timeZoneName.CentralUS), _
'        New locationClass("EBJ", timeZoneName.CentralEuropean), _
'        New locationClass("EDI", timeZoneName.GreenwichMeanTime), _
'        New locationClass("EGE", timeZoneName.MountainUS), _
'        New locationClass("EIS", timeZoneName.AtlanticUS), _
'        New locationClass("ELH", timeZoneName.EasternUS), _
'        New locationClass("ELS", timeZoneName.GreenwichMeanTime), _
'        New locationClass("ELM", timeZoneName.EasternUS), _
'        New locationClass("ELP", timeZoneName.CentralUS), _
'        New locationClass("ERI", timeZoneName.EasternUS), _
'        New locationClass("ESB", timeZoneName.Cairo), _
'        New locationClass("EUG", timeZoneName.PacificUS), _
'        New locationClass("EUX", timeZoneName.AtlanticUS), _
'        New locationClass("EVV", timeZoneName.CentralUS), _
'        New locationClass("EWN", timeZoneName.EasternUS), _
'        New locationClass("EWR", timeZoneName.EasternUS), _
'        New locationClass("EYW", timeZoneName.EasternUS), _
'        New locationClass("EZE", timeZoneName.BuenosAires), _
'        New locationClass("FAE", timeZoneName.GreenwichMeanTime), _
'        New locationClass("FAR", timeZoneName.CentralUS), _
'        New locationClass("FAT", timeZoneName.PacificUS), _
'        New locationClass("FAY", timeZoneName.EasternUS), _
'        New locationClass("FBU", timeZoneName.CentralEuropean), _
'        New locationClass("FCO", timeZoneName.CentralEuropean), _
'        New locationClass("FKL", timeZoneName.EasternUS), _
'        New locationClass("FLL", timeZoneName.EasternUS), _
'        New locationClass("FLO", timeZoneName.EasternUS), _
'        New locationClass("FNL", timeZoneName.MountainUS), _
'        New locationClass("FNT", timeZoneName.EasternUS), _
'        New locationClass("FOE", timeZoneName.CentralUS), _
'        New locationClass("FPO", timeZoneName.EasternUS), _
'        New locationClass("FRA", timeZoneName.CentralEuropean), _
'        New locationClass("FSD", timeZoneName.CentralUS), _
'        New locationClass("FWA", timeZoneName.Indiana), _
'        New locationClass("GBD", timeZoneName.CentralUS), _
'        New locationClass("GCC", timeZoneName.MountainUS), _
'        New locationClass("GCK", timeZoneName.CentralUS), _
'        New locationClass("GCM", timeZoneName.EasternUS), _
'        New locationClass("GDL", timeZoneName.MexicoCity), _
'        New locationClass("GDN", timeZoneName.CentralEuropean), _
'        New locationClass("GEN", timeZoneName.CentralEuropean), _
'        New locationClass("GHB", timeZoneName.EasternUS), _
'        New locationClass("GIG", timeZoneName.Brasilia), _
'        New locationClass("GLA", timeZoneName.GreenwichMeanTime), _
'        New locationClass("GJT", timeZoneName.MountainUS), _
'        New locationClass("GNV", timeZoneName.EasternUS), _
'        New locationClass("GOT", timeZoneName.CentralEuropean), _
'        New locationClass("GRB", timeZoneName.CentralUS), _
'        New locationClass("GRI", timeZoneName.CentralUS), _
'        New locationClass("GPT", timeZoneName.CentralUS), _
'        New locationClass("GRR", timeZoneName.EasternUS), _
'        New locationClass("GRU", timeZoneName.Brasilia), _
'        New locationClass("GSO", timeZoneName.EasternUS), _
'        New locationClass("GSP", timeZoneName.EasternUS), _
'        New locationClass("GTF", timeZoneName.MountainUS), _
'        New locationClass("GUA", timeZoneName.CentralAmerica), _
'        New locationClass("GUC", timeZoneName.MountainUS), _
'        New locationClass("GUM", timeZoneName.Pacific), _
'        New locationClass("GVA", timeZoneName.CentralEuropean), _
'        New locationClass("GYE", timeZoneName.BogotaLima), _
'        New locationClass("HAJ", timeZoneName.CentralEuropean), _
'        New locationClass("HAM", timeZoneName.CentralEuropean), _
'        New locationClass("HDN", timeZoneName.MountainUS), _
'        New locationClass("HEL", timeZoneName.HelsinkiRiga), _
'        New locationClass("HIJ", timeZoneName.TokyoOsaka), _
'        New locationClass("HGR", timeZoneName.EasternUS), _
'        New locationClass("HHH", timeZoneName.EasternUS), _
'        New locationClass("HHP", timeZoneName.HongKong), _
'        New locationClass("HKG", timeZoneName.HongKong), _
'        New locationClass("HKY", timeZoneName.EasternUS), _
'        New locationClass("HNL", timeZoneName.Hawaii), _
'        New locationClass("HOU", timeZoneName.CentralUS), _
'        New locationClass("HPN", timeZoneName.EasternUS), _
'        New locationClass("HRL", timeZoneName.CentralUS), _
'        New locationClass("HSV", timeZoneName.CentralUS), _
'        New locationClass("HTS", timeZoneName.EasternUS), _
'        New locationClass("HVN", timeZoneName.EasternUS), _
'        New locationClass("HYA", timeZoneName.EasternUS), _
'        New locationClass("HYS", timeZoneName.CentralUS), _
'        New locationClass("IAD", timeZoneName.EasternUS), _
'        New locationClass("IAH", timeZoneName.CentralUS), _
'        New locationClass("ICN", timeZoneName.Asia), _
'        New locationClass("ICT", timeZoneName.CentralUS), _
'        New locationClass("IFP", timeZoneName.MountainUS), _
'        New locationClass("ILM", timeZoneName.EasternUS), _
'        New locationClass("IND", timeZoneName.EasternUS), _
'        New locationClass("INV", timeZoneName.GreenwichMeanTime), _
'        New locationClass("IPT", timeZoneName.EasternUS), _
'        New locationClass("IQT", timeZoneName.BogotaLima), _
'        New locationClass("ISB", timeZoneName.Islamabad), _
'        New locationClass("ISP", timeZoneName.EasternUS), _
'        New locationClass("IST", timeZoneName.AthensIstanbul), _
'        New locationClass("ITH", timeZoneName.EasternUS), _
'        New locationClass("ITO", timeZoneName.Hawaii), _
'        New locationClass("JAN", timeZoneName.CentralUS), _
'        New locationClass("JAX", timeZoneName.EasternUS), _
'        New locationClass("JEC", timeZoneName.EasternUS), _
'        New locationClass("JED", timeZoneName.AbuDhabi), _
'        New locationClass("JFK", timeZoneName.EasternUS), _
'        New locationClass("JHW", timeZoneName.EasternUS), _
'        New locationClass("JKT", timeZoneName.BankokHanoi), _
'        New locationClass("JNB", timeZoneName.PacificUS), _
'        New locationClass("JON", timeZoneName.CapeTown), _
'        New locationClass("JST", timeZoneName.EasternUS), _
'        New locationClass("KBP", timeZoneName.EasternEuropean), _
'        New locationClass("KEF", timeZoneName.GreenwichMeanTime), _
'        New locationClass("KIX", timeZoneName.TokyoOsaka), _
'        New locationClass("KOA", timeZoneName.PacificUS), _
'        New locationClass("KTM", timeZoneName.SriLanka), _
'        New locationClass("KUL", timeZoneName.HongKong), _
'        New locationClass("KWA", timeZoneName.Kwajalein), _
'        New locationClass("KWI", timeZoneName.Moscow), _
'        New locationClass("LAS", timeZoneName.PacificUS), _
'        New locationClass("LAX", timeZoneName.PacificUS), _
'        New locationClass("LBA", timeZoneName.GreenwichMeanTime), _
'        New locationClass("LBE", timeZoneName.EasternUS), _
'        New locationClass("LBF", timeZoneName.CentralUS), _
'        New locationClass("LCA", timeZoneName.EasternEuropean), _
'        New locationClass("LCK", timeZoneName.EasternUS), _
'        New locationClass("LEB", timeZoneName.EasternUS), _
'        New locationClass("LED", timeZoneName.CentralEuropean), _
'        New locationClass("LEX", timeZoneName.EasternUS), _
'        New locationClass("LGA", timeZoneName.EasternUS), _
'        New locationClass("LGB", timeZoneName.PacificUS), _
'        New locationClass("LGW", timeZoneName.GreenwichMeanTime), _
'        New locationClass("LHE", timeZoneName.Islamabad), _
'        New locationClass("LHR", timeZoneName.GreenwichMeanTime), _
'        New locationClass("LIH", timeZoneName.Hawaii), _
'        New locationClass("LIM", timeZoneName.BogotaLima), _
'        New locationClass("LIN", timeZoneName.CentralEuropean), _
'        New locationClass("LIS", timeZoneName.GreenwichMeanTime), _
'        New locationClass("LIT", timeZoneName.CentralUS), _
'        New locationClass("LJU", timeZoneName.CentralEuropean), _
'        New locationClass("LMZ", timeZoneName.CentralEuropean), _
'        New locationClass("LNK", timeZoneName.CentralUS), _
'        New locationClass("LNS", timeZoneName.EasternUS), _
'        New locationClass("LOU", timeZoneName.EasternUS), _
'        New locationClass("LPB", timeZoneName.Carcas), _
'        New locationClass("LRM", timeZoneName.AtlanticUS), _
'        New locationClass("LSE", timeZoneName.CentralUS), _
'        New locationClass("LUX", timeZoneName.HongKong), _
'        New locationClass("LWB", timeZoneName.EasternUS), _
'        New locationClass("LYH", timeZoneName.EasternUS), _
'        New locationClass("LYN", timeZoneName.CentralEuropean), _
'        New locationClass("MAD", timeZoneName.CentralEuropean), _
'        New locationClass("MAJ", timeZoneName.Kwajalein), _
'        New locationClass("MAN", timeZoneName.GreenwichMeanTime), _
'        New locationClass("MAO", timeZoneName.BogotaLima), _
'        New locationClass("MAR", timeZoneName.Carcas), _
'        New locationClass("MBJ", timeZoneName.EasternUS), _
'        New locationClass("MBS", timeZoneName.EasternUS), _
'        New locationClass("MCI", timeZoneName.CentralUS), _
'        New locationClass("MCO", timeZoneName.EasternUS), _
'        New locationClass("MCT", timeZoneName.BakuTblisi), _
'        New locationClass("MDT", timeZoneName.EasternUS), _
'        New locationClass("MDW", timeZoneName.CentralUS), _
'        New locationClass("MEL", timeZoneName.EasternAustralian), _
'        New locationClass("MEM", timeZoneName.CentralUS), _
'        New locationClass("MEX", timeZoneName.MexicoCity), _
'        New locationClass("MFR", timeZoneName.PacificUS), _
'        New locationClass("MGA", timeZoneName.CentralAmerica), _
'        New locationClass("MGM", timeZoneName.CentralUS), _
'        New locationClass("MGW", timeZoneName.EasternUS), _
'        New locationClass("MHH", timeZoneName.EasternUS), _
'        New locationClass("MHK", timeZoneName.CentralUS), _
'        New locationClass("MHT", timeZoneName.EasternUS), _
'        New locationClass("MIA", timeZoneName.EasternUS), _
'        New locationClass("MLA", timeZoneName.CentralEuropean), _
'        New locationClass("MKE", timeZoneName.CentralUS), _
'        New locationClass("MKK", timeZoneName.Hawaii), _
'        New locationClass("MLI", timeZoneName.CentralUS), _
'        New locationClass("MMA", timeZoneName.CentralEuropean), _
'        New locationClass("MNL", timeZoneName.MalaysiaSingapore), _
'        New locationClass("MOB", timeZoneName.CentralUS), _
'        New locationClass("MOW", timeZoneName.Moscow), _
'        New locationClass("MRY", timeZoneName.PacificUS), _
'        New locationClass("MSN", timeZoneName.CentralUS), _
'        New locationClass("MSP", timeZoneName.CentralUS), _
'        New locationClass("MSS", timeZoneName.EasternUS), _
'        New locationClass("MSY", timeZoneName.CentralUS), _
'        New locationClass("MTJ", timeZoneName.MountainUS), _
'        New locationClass("MUC", timeZoneName.CentralEuropean), _
'        New locationClass("MVD", timeZoneName.Brasilia), _
'        New locationClass("MVY", timeZoneName.EasternUS), _
'        New locationClass("MXD", timeZoneName.EasternAustralian), _
'        New locationClass("MXP", timeZoneName.CentralEuropean), _
'        New locationClass("MYR", timeZoneName.EasternUS), _
'        New locationClass("MZT", timeZoneName.MexicoCity), _
'        New locationClass("NAS", timeZoneName.EasternUS), _
'        New locationClass("NAN", timeZoneName.FijiIslands), _
'        New locationClass("NAP", timeZoneName.CentralEuropean), _
'        New locationClass("NCE", timeZoneName.CentralEuropean), _
'        New locationClass("NEV", timeZoneName.AtlanticUS), _
'        New locationClass("NRT", timeZoneName.TokyoOsaka), _
'        New locationClass("NUE", timeZoneName.CentralEuropean), _
'        New locationClass("OAJ", timeZoneName.EasternUS), _
'        New locationClass("OAK", timeZoneName.PacificUS), _
'        New locationClass("OGG", timeZoneName.Hawaii), _
'        New locationClass("OGS", timeZoneName.EasternUS), _
'        New locationClass("OKC", timeZoneName.CentralUS), _
'        New locationClass("OMA", timeZoneName.CentralUS), _
'        New locationClass("ONT", timeZoneName.PacificUS), _
'        New locationClass("ORD", timeZoneName.CentralUS), _
'        New locationClass("ORF", timeZoneName.EasternUS), _
'        New locationClass("ORY", timeZoneName.CentralEuropean), _
'        New locationClass("OSL", timeZoneName.CentralEuropean), _
'        New locationClass("OTP", timeZoneName.CentralEuropean), _
'        New locationClass("PBI", timeZoneName.EasternUS), _
'        New locationClass("PDX", timeZoneName.PacificUS), _
'        New locationClass("PEK", timeZoneName.HongKong), _
'        New locationClass("PER", timeZoneName.Perth), _
'        New locationClass("PFN", timeZoneName.CentralUS), _
'        New locationClass("PGV", timeZoneName.EasternUS), _
'        New locationClass("PHF", timeZoneName.EasternUS), _
'        New locationClass("PHL", timeZoneName.EasternUS), _
'        New locationClass("PHX", timeZoneName.Arizona), _
'        New locationClass("PIA", timeZoneName.CentralUS), _
'        New locationClass("PIE", timeZoneName.EasternUS), _
'        New locationClass("PIT", timeZoneName.EasternUS), _
'        New locationClass("PKB", timeZoneName.EasternUS), _
'        New locationClass("PLS", timeZoneName.EasternUS), _
'        New locationClass("PMI", timeZoneName.CentralEuropean), _
'        New locationClass("PNS", timeZoneName.CentralUS), _
'        New locationClass("POS", timeZoneName.Carcas), _
'        New locationClass("PPG", timeZoneName.SamoaMidway), _
'        New locationClass("PPT", timeZoneName.Hawaii), _
'        New locationClass("PQI", timeZoneName.EasternUS), _
'        New locationClass("PRG", timeZoneName.CentralEuropean), _
'        New locationClass("PSE", timeZoneName.AtlanticUS), _
'        New locationClass("PSP", timeZoneName.PacificUS), _
'        New locationClass("PTY", timeZoneName.BogotaLima), _
'        New locationClass("PUJ", timeZoneName.AtlanticUS), _
'        New locationClass("PUS", timeZoneName.Asia), _
'        New locationClass("PVD", timeZoneName.EasternUS), _
'        New locationClass("PVG", timeZoneName.HongKong), _
'        New locationClass("PVR", timeZoneName.MexicoCity), _
'        New locationClass("PWM", timeZoneName.EasternUS), _
'        New locationClass("RAP", timeZoneName.MountainUS), _
'        New locationClass("RAR", timeZoneName.Hawaii), _
'        New locationClass("RDG", timeZoneName.EasternUS), _
'        New locationClass("RDU", timeZoneName.EasternUS), _
'        New locationClass("RFD", timeZoneName.CentralUS), _
'        New locationClass("RIC", timeZoneName.EasternUS), _
'        New locationClass("RIX", timeZoneName.HelsinkiRiga), _
'        New locationClass("RIO", timeZoneName.BuenosAires), _
'        New locationClass("RKD", timeZoneName.EasternUS), _
'        New locationClass("RNO", timeZoneName.PacificUS), _
'        New locationClass("ROA", timeZoneName.EasternUS), _
'        New locationClass("ROC", timeZoneName.EasternUS), _
'        New locationClass("ROM", timeZoneName.CentralEuropean), _
'        New locationClass("RST", timeZoneName.CentralUS), _
'        New locationClass("RSU", timeZoneName.Asia), _
'        New locationClass("RSW", timeZoneName.EasternUS), _
'        New locationClass("RUH", timeZoneName.AbuDhabi), _
'        New locationClass("SAB", timeZoneName.AtlanticUS), _
'        New locationClass("SAL", timeZoneName.CentralAmerica), _
'        New locationClass("SAN", timeZoneName.PacificUS), _
'        New locationClass("SAP", timeZoneName.CentralAmerica), _
'        New locationClass("SAT", timeZoneName.CentralUS), _
'        New locationClass("SAV", timeZoneName.EasternUS), _
'        New locationClass("SIA", timeZoneName.MalaysiaSingapore), _
'        New locationClass("SIN", timeZoneName.MalaysiaSingapore), _
'        New locationClass("SIG", timeZoneName.AtlanticUS), _
'        New locationClass("SBA", timeZoneName.PacificUS), _
'        New locationClass("SBH", timeZoneName.AtlanticUS), _
'        New locationClass("SBN", timeZoneName.Indiana), _
'        New locationClass("SBY", timeZoneName.EasternUS), _
'        New locationClass("SCE", timeZoneName.EasternUS), _
'        New locationClass("SCL", timeZoneName.Brasilia), _
'        New locationClass("SDA", timeZoneName.Bagdad), _
'        New locationClass("SDF", timeZoneName.EasternUS), _
'        New locationClass("SDQ", timeZoneName.AtlanticUS), _
'        New locationClass("SEA", timeZoneName.PacificUS), _
'        New locationClass("SEL", timeZoneName.Asia), _
'        New locationClass("SFO", timeZoneName.PacificUS), _
'        New locationClass("SGF", timeZoneName.CentralUS), _
'        New locationClass("SGN", timeZoneName.BankokHanoi), _
'        New locationClass("SGT", timeZoneName.CentralEuropean), _
'        New locationClass("SHA", timeZoneName.HongKong), _
'        New locationClass("SHD", timeZoneName.EasternUS), _
'        New locationClass("SHV", timeZoneName.CentralUS), _
'        New locationClass("SJC", timeZoneName.PacificUS), _
'        New locationClass("SJD", timeZoneName.MexicoCity), _
'        New locationClass("SJJ", timeZoneName.CentralEuropean), _
'        New locationClass("SJN", timeZoneName.MountainUS), _
'        New locationClass("SJO", timeZoneName.CentralAmerica), _
'        New locationClass("SJU", timeZoneName.AtlanticUS), _
'        New locationClass("SKB", timeZoneName.AtlanticUS), _
'        New locationClass("SLC", timeZoneName.MountainUS), _
'        New locationClass("SLN", timeZoneName.CentralUS), _
'        New locationClass("SMF", timeZoneName.PacificUS), _
'        New locationClass("SMP", timeZoneName.CentralEuropean), _
'        New locationClass("SNA", timeZoneName.PacificUS), _
'        New locationClass("SOF", timeZoneName.EasternEuropean), _
'        New locationClass("SPI", timeZoneName.CentralUS), _
'        New locationClass("SRQ", timeZoneName.EasternUS), _
'        New locationClass("SRZ", timeZoneName.Carcas), _
'        New locationClass("STL", timeZoneName.CentralUS), _
'        New locationClass("STT", timeZoneName.AtlanticUS), _
'        New locationClass("STX", timeZoneName.AtlanticUS), _
'        New locationClass("SUG", timeZoneName.CentralEuropean), _
'        New locationClass("SUX", timeZoneName.CentralUS), _
'        New locationClass("SVG", timeZoneName.CentralEuropean), _
'        New locationClass("SVO", timeZoneName.Moscow), _
'        New locationClass("SWF", timeZoneName.EasternUS), _
'        New locationClass("SXM", timeZoneName.AtlanticUS), _
'        New locationClass("SYD", timeZoneName.EasternAustralian), _
'        New locationClass("SYR", timeZoneName.EasternUS), _
'        New locationClass("TCB", timeZoneName.EasternUS), _
'        New locationClass("TBU", timeZoneName.Tonga), _
'        New locationClass("TGU", timeZoneName.CentralAmerica), _
'        New locationClass("THR", timeZoneName.Tehran), _
'        New locationClass("TLH", timeZoneName.EasternUS), _
'        New locationClass("TLL", timeZoneName.HelsinkiRiga), _
'        New locationClass("TOL", timeZoneName.EasternUS), _
'        New locationClass("TPA", timeZoneName.EasternUS), _
'        New locationClass("TPE", timeZoneName.MalaysiaSingapore), _
'        New locationClass("TRI", timeZoneName.EasternUS), _
'        New locationClass("TTN", timeZoneName.EasternUS), _
'        New locationClass("TUL", timeZoneName.CentralUS), _
'        New locationClass("TUN", timeZoneName.Azores), _
'        New locationClass("TXL", timeZoneName.CentralEuropean), _
'        New locationClass("TYS", timeZoneName.EasternUS), _
'        New locationClass("UIO", timeZoneName.BogotaLima), _
'        New locationClass("UVF", timeZoneName.AtlanticUS), _
'        New locationClass("VPS", timeZoneName.CentralUS), _
'        New locationClass("VCE", timeZoneName.CentralEuropean), _
'        New locationClass("VCP", timeZoneName.Brasilia), _
'        New locationClass("VGS", timeZoneName.EasternUS), _
'        New locationClass("VGZ", timeZoneName.Brasilia), _
'        New locationClass("VIE", timeZoneName.CentralEuropean), _
'        New locationClass("VLN", timeZoneName.Carcas), _
'        New locationClass("VNC", timeZoneName.CentralEuropean), _
'        New locationClass("VNO", timeZoneName.HelsinkiRiga), _
'        New locationClass("VQS", timeZoneName.AtlanticUS), _
'        New locationClass("WAW", timeZoneName.CentralEuropean), _
'        New locationClass("XNA", timeZoneName.CentralUS), _
'        New locationClass("YBB", timeZoneName.MountainUS), _
'        New locationClass("YBK", timeZoneName.CentralUS), _
'        New locationClass("YCB", timeZoneName.MountainUS), _
'        New locationClass("YCK", timeZoneName.MountainUS), _
'        New locationClass("YCO", timeZoneName.MountainUS), _
'        New locationClass("YCS", timeZoneName.MountainUS), _
'        New locationClass("YDQ", timeZoneName.MountainUS), _
'        New locationClass("YEG", timeZoneName.MountainUS), _
'        New locationClass("YEK", timeZoneName.CentralUS), _
'        New locationClass("YEV", timeZoneName.MountainUS), _
'        New locationClass("YFB", timeZoneName.EasternUS), _
'        New locationClass("YFJ", timeZoneName.EasternUS), _
'        New locationClass("YFS", timeZoneName.MountainUS), _
'        New locationClass("YGH", timeZoneName.MountainUS), _
'        New locationClass("YGT", timeZoneName.EasternUS), _
'        New locationClass("YGZ", timeZoneName.EasternUS), _
'        New locationClass("YHI", timeZoneName.MountainUS), _
'        New locationClass("YHK", timeZoneName.MountainUS), _
'        New locationClass("YHY", timeZoneName.MountainUS), _
'        New locationClass("YHZ", timeZoneName.AtlanticUS), _
'        New locationClass("YIO", timeZoneName.EasternUS), _
'        New locationClass("YKA", timeZoneName.PacificUS), _
'        New locationClass("YLC", timeZoneName.EasternUS), _
'        New locationClass("YLE", timeZoneName.MountainUS), _
'        New locationClass("YLW", timeZoneName.PacificUS), _
'        New locationClass("YNY", timeZoneName.Asia), _
'        New locationClass("YOA", timeZoneName.MountainUS), _
'        New locationClass("YOW", timeZoneName.EasternUS), _
'        New locationClass("YPC", timeZoneName.MountainUS), _
'        New locationClass("YQR", timeZoneName.CentralUS), _
'        New locationClass("YRA", timeZoneName.MountainUS), _
'        New locationClass("YRB", timeZoneName.EasternUS), _
'        New locationClass("YRT", timeZoneName.CentralUS), _
'        New locationClass("YSG", timeZoneName.MountainUS), _
'        New locationClass("YSM", timeZoneName.MountainUS), _
'        New locationClass("YSY", timeZoneName.MountainUS), _
'        New locationClass("YUB", timeZoneName.CentralUS), _
'        New locationClass("YUL", timeZoneName.EasternUS), _
'        New locationClass("YUT", timeZoneName.CentralUS), _
'        New locationClass("YVQ", timeZoneName.MountainUS), _
'        New locationClass("YVR", timeZoneName.PacificUS), _
'        New locationClass("YWG", timeZoneName.CentralUS), _
'        New locationClass("YWJ", timeZoneName.MountainUS), _
'        New locationClass("YXE", timeZoneName.CentralUS), _
'        New locationClass("YXN", timeZoneName.CentralUS), _
'        New locationClass("YXP", timeZoneName.EasternUS), _
'        New locationClass("YYC", timeZoneName.MountainUS), _
'        New locationClass("YYH", timeZoneName.CentralUS), _
'        New locationClass("YYQ", timeZoneName.CentralUS), _
'        New locationClass("YYT", timeZoneName.EasternUS), _
'        New locationClass("YYZ", timeZoneName.EasternUS), _
'        New locationClass("YZF", timeZoneName.MountainUS), _
'        New locationClass("YZS", timeZoneName.EasternUS), _
'        New locationClass("ZAG", timeZoneName.CentralEuropean), _
'        New locationClass("ZFM", timeZoneName.MountainUS), _
'        New locationClass("ZFN", timeZoneName.MountainUS), _
'        New locationClass("ZHG", timeZoneName.Cairo), _
'        New locationClass("ZIH", timeZoneName.MexicoCity), _
'        New locationClass("ZLO", timeZoneName.MexicoCity), _
'        New locationClass("ZRH", timeZoneName.CentralEuropean)}

'    Public airportCodeList() As String

'    Private Shared singlet As airportSetClass

'    Private Sub New()

'        Dim airport As locationClass

'        Dim airportListLength As Integer = Me.airportList.Length
'        Dim ilmt As Integer = airportListLength - 1

'        ReDim airportCodeList(ilmt)

'        Dim i As Integer

'        For i = 0 To ilmt
'            airportCodeList(i) = Me.airportList(i).locationCode
'        Next

'        Array.Sort(airportCodeList)

'        For Each airport In Me.airportList
'            Me.Add(airport.locationCode, airport)
'        Next

'    End Sub

'End Class
